name: Run Hours Suite

on:
  workflow_dispatch:       # allows manual trigger
    inputs:
      suite:
        description: "Choose which TestNG suite to run"
        required: true
        default: "testng.xml"
        type: choice
        options:
          - Jamaica.xml
          - Panama.xml
          - CostaRica.xml
          - Colombia.xml
          - International.xml
          - testng.xml

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    

      - name: Run TestNG Suite
        run: |
          echo "Running suite: ${{ github.event.inputs.suite }}"
          mvn clean test -DsuiteXmlFile=${{ github.event.inputs.suite }} -Dselenide.headless=true
        continue-on-error: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: allure-history


      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # Upload Selenide screenshots / test reports
      - name: Upload Test Screenshots and Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: build/reports/tests/


          
